name: Weekly Job for tm-bot

on:
  schedule:
    # Запуск каждую среду в 7:30 утра по UTC
    - cron: '30 7 * * 3'

jobs:
  run-on-server:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверяем исходный код (необязательно, если работа идёт только на сервере)
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Подключаемся к серверу и выполняем команды
      - name: Execute commands on server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Setting up SSH connection..."
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no username@your_server_ip << 'EOF'
            cd /var/www/tg_match/tm-bot
            npm install
            npm run start
          EOF
