name: Scheduled Job

on:
  schedule:
    # Запуск каждую среду в 7:30 утра по UTC
    - cron: '30 7 * * 3'

  push:
    branches:
      - scheduler # Срабатывает, если происходит push в ветку scheduler

jobs:
  run-on-server:
    if: github.ref == 'refs/heads/scheduler' # Проверяет, что текущая ветка scheduler
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute commands on server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Setting up SSH connection..."
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no root@@162.55.219.246 << 'EOF'
            cd /var/www/tg_match/tm-bot
            npm install
            npm run start
          EOF
